name: Deploy Containerized Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: publish
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@master
        with:
          args: apply -f deployment.yaml,service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}