name: Publish Docker Image to Registry and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t deploy-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag deploy-app ${{ secrets.DOCKER_USERNAME }}/deploy-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/deploy-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@master
        with:
          args: apply -f deployment.yaml,service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}